Patch pointer
Fluorohydride/ygopro pull request #2551
Opened 2024-05-21 09:40 UTC by salix5

-  use memcpy in DuelClient, NetServer 
-  replace memcpy with std::memcpy 

# Buffer overflow in current version
Before:
The server will copy `packet_len + 2` bytes to buffer, where `packet_len` is sent by the client.
It will suffer from buffer overflow if the client sends a very large packet.
(crash and/or security issues)

Now:
The server will discard too large packet.

@mercury233 
@purerosefallen

2024-05-26 08:33 UTC, salix5 commented
@edo9300 
I think edopro has the same problems too.
Can you take a look?
Thank you!

2024-05-26 15:16 UTC, edo9300 commented
> @edo9300 I think edopro has the same problems too. Can you take a look? Thank you!

Thanks for the concern, in my case no static buffers are being used, so buffer overruns shouldn't happen in this scenario, _what would happen would be a bad alloc exception being raised and the program crashing if there won't be enough memory available for the vector_

2024-05-26 16:37 UTC, salix5 commented
@edo9300 
https://github.com/edo9300/edopro/blob/master/gframe/netserver.h
It seems that `net_server_read` and `net_server_write` are still static arrays.

2024-05-27 03:55 UTC, purerosefallen commented
@salix5 In the past there are multiple cases that adding `std::` to `memcpy` would make it fail to build on Linux and Mac.

Could you please test them?

2024-05-27 05:53 UTC, salix5 commented
> @salix5 In the past there are multiple cases that adding `std::` to `memcpy` would make it fail to build on Linux and Mac.
> 
> Could you please test them?
> 
> Also please do a favor to make a merge to mycard/ygopro:server.

Now `std::memcpy` is included in every file of gframe.
#include <cstring> in ocgcore/buffer.h
#include "../ocgcore/buffer.h" in gframe/bufferio.h
#include "bufferio.h" in gframe/config.h

2024-05-28 01:46 UTC, purerosefallen commented on gframe/deck_con.cpp
> +	int maxc = mainGame->is_siding ? 64 : DECK_MAX_SIZE;
Use dynamic way.

`int maxc = mainGame->is_siding ? DECK_MAX_SIZE + 4 : DECK_MAX_SIZE;`

2024-05-28 01:48 UTC, purerosefallen requested changes
Please change it to dynamic way in deck_con.cpp

2024-05-30 09:25 UTC, purerosefallen commented
It seemed that the old client cannot connect to new server at all.

Related third-party clients should make some changes, including WindBot and YGOPro2. But we still had no idea on what to change.

2024-05-30 10:52 UTC, DailyShana commented
I think the main problem is this one PR do so many things, which make other maintainer hard to review.

The easy part like adding `std::` and use memcpy to avoid pointer cast can be split to another PR and be merged smoothly.

Checking length of deck data can be a another PR because it does not touch server things.
Checking lengh of STOC data should be another PR without changing structure of STOC
Although all above are about checking length of data, they are data of different facilities, split into different PR will make easier to review.

Changing or removing STOC structure will break compatibiliy, this part should be a single PR with fully discussion before merging.
By the way, I can't understand the reason above why to remove STOC_Chat

2024-05-30 11:02 UTC, salix5 commented
> I think the main problem is this one PR do so many things, which make other maintainer hard to review.
> 
> The easy part like adding `std::` and use memcpy to avoid pointer cast can be split to another PR and be merged smoothly.
> 
> Checking length of deck data can be a another PR because it does not touch server things. Checking lengh of STOC data should be another PR without changing structure of STOC Although all above are about checking length of data, they are data of different facilities, split into different PR will make easier to review.
Maybe you can convince @purerosefallen  that we can open a new PR.

> Changing or removing STOC structure will break compatibiliy, this part should be a single PR with fully discussion before merging. By the way, I can't understand the reason above why to remove STOC_Chat
No, it does not.
Other clients still send the STOC_CHAT packet in the same way:
uint16_t  player_type, 2B
uint16_t msg, 1 ~ 256 code units

Casting to `struct STOC_Chat` is simply wrong.
The msg is not a fixed-size array `msg[256]`.
It never has been.
It is just a byte buffer which contains 1~256 `uint16_t` code units.

I removed it because no one really use that.

2024-05-30 11:36 UTC, salix5 commented
#2555
remove the irrelevant commit
If you still think it is still too much, that it because ygopro has so many problems in the past ten years.

2024-05-30 12:13 UTC, purerosefallen commented
> #2555 remove the irrelevant commit If you still think it is still too much, that it because ygopro has so many problems in the past ten years.

I would continue to talk on this PR rather than #2551.
When we merge it we could squash it ignoring that tons of mid-commits.

In addition, some server implementations such as SRVPro, sends STOC_HS_PlayerEnter as 41 bytes without the tailing padding. Could we support those cases?

2024-05-30 12:18 UTC, purerosefallen commented
> I think the main problem is this one PR do so many things, which make other maintainer hard to review.
> 
> The easy part like adding `std::` and use memcpy to avoid pointer cast can be split to another PR and be merged smoothly.
> 
> Checking length of deck data can be a another PR because it does not touch server things. Checking lengh of STOC data should be another PR without changing structure of STOC Although all above are about checking length of data, they are data of different facilities, split into different PR will make easier to review.
> 
> Changing or removing STOC structure will break compatibiliy, this part should be a single PR with fully discussion before merging. By the way, I can't understand the reason above why to remove STOC_Chat

In case we do breaking changes we would change the version number.

In addition, if splitting a PR into multiple PRs, how do you make sure those PRs don't touch each other? It's even harder to review.

2024-05-30 12:30 UTC, edo9300 commented
Fwiw, on my end i retrieve stoc structs this way 
```cpp
template<typename T>
static T getStruct(const void* data, size_t len) {
	T pkt{};
	memcpy(&pkt, data, std::min(sizeof(T), len));
	return pkt;
}
```
Allowing to perform short reads as well, leaving the rest of the struct zero initialized, in the case of STOC_Chat, it will support reading a chat message that doesn't send the whole buffer for example.

2024-05-30 18:13 UTC, salix5 commented
> Fwiw, on my end i retrieve stoc structs this way
> 
> ```c++
> template<typename T>
> static T getStruct(const void* data, size_t len) {
> 	T pkt{};
> 	memcpy(&pkt, data, std::min(sizeof(T), len));
> 	return pkt;
> }
> ```
> 
> Allowing to perform short reads as well, leaving the rest of the struct zero initialized, in the case of STOC_Chat, it will support reading a chat message that doesn't send the whole buffer for example.

Thank you for your advice.

My opinion:
If the size of the `uint16_t` array is not fixed, we do not need a `struct` in the first place.
We can just keep the record of the max length of this array in `LEN_CHAT_MSG`.

```cpp
std::memcpy(player, pdata, LEN_CHAT_PLAYER*sizeof(uint16_t));
std::memcpy(msg, pdata, LEN_CHAT_MSG*sizeof(uint16_t));
```
Actually, it is much better than reading/writing `struct` to the network buffer directly because `struct` has padding.

2024-05-30 18:35 UTC, edo9300 commented
Having a struct to define a network packet is way better than writing raw buffers, as you have a clear representation of what you're sending/receiving, in fact that's one of the main things that make the ygopro network infrastructure had to deal with. Regarding padding, that's really not an issue as it's clearly defined by the c/c++ standard, and sending 2 extra bytes won't cause any harm

2024-05-30 19:46 UTC, salix5 commented
C++14 / N4140

5.3.3 Sizeof [expr.sizeof]
item 2
When applied to a class, the result is the number of bytes in an object of that class including any padding required for placing objects of that type in an array.


9.2 Class members [class.mem]
item 13
Nonstatic data members of a (non-union) class with the same access control (Clause 11) are allocated so that later members have higher addresses within a class object. 
The order of allocation of non-static data members with different access control is unspecified (Clause 11).
Implementation alignment requirements might cause two adjacent members not to be allocated immediately after each other; so might requirements for space for managing virtual functions (10.3) and virtual base classes (10.1).

It seems that the size of padding in a POD class is implementation-defined.
I did not find the explicit definition of size and location of padding in a POD class from the C++ standard.

@purerosefallen also mentions that 
```cpp
struct STOC_HS_PlayerEnter {
	unsigned short name[20];
	unsigned char pos;
	// byte padding[1]
};
static_assert(sizeof(STOC_HS_PlayerEnter) == 42, "size mismatch: STOC_HS_PlayerEnter");
```
The assertion may fail in some implementation.

2024-05-30 23:29 UTC, salix5 commented
C++14 / N4140
3.9 Types [basic.types]
item 2
For any object (other than a base-class subobject) of trivially copyable type T, whether or not the object
holds a valid value of type T, the underlying bytes (1.7) making up the object can be copied into an array
of char or unsigned char.(42)
If the content of the array of char or unsigned char is copied back into theobject, the object shall subsequently hold its original value.

9 Classes [class]
item 6
A trivially copyable class is a class that:
(6.1) — has no non-trivial copy constructors (12.8),
(6.2) — has no non-trivial move constructors (12.8),
(6.3) — has no non-trivial copy assignment operators (13.5.3, 12.8),
(6.4) — has no non-trivial move assignment operators (13.5.3, 12.8), and
(6.5) — has a trivial destructor (12.4).

https://en.cppreference.com/w/cpp/types/is_trivially_copyable
template< class T >
struct is_trivially_copyable;

My conclusion:
If one really want to send a `struct` in a byte array, the minimal requirements are:
- It must be trivially copyable
checked by `static_assert(std::is_trivially_copyable<T>::value == true, "not trivially copyable")`

- The size must be a fixed value
checked by static_assert

- The padding must be the same
It seems that there are certain rules of data alignment in x86 system.
Other than that? Good luck.

- The endianness must be the same
(Almost) everyone uses little-endian system.
If not? Good luck.

Now we can safely write
```cpp
std::memcpy(&pkt, data, sizeof(T));
```

What happens if we write:
```cpp
std::memcpy(&pkt, data, sizeof(T)/2);
```

I do not know. Good luck.

2024-05-30 23:33 UTC, purerosefallen commented
Can we support STOC_HS_Player_Enter with 41 bytes for now? Then we may have some time to change every server implementation and deprecate that 41-byte message as time goes by.

2024-05-30 23:52 UTC, salix5 commented
> Can we support STOC_HS_Player_Enter with 41 bytes for now? Then we may have some time to change every server implementation and deprecate that 41-byte message as time goes by.

done
It will check STOC_HS_PlayerEnter_size (41) for now.

2024-05-31 02:51 UTC, purerosefallen commented
Just a little more thought.

how about `#pragma pack(1)` on `STOC_HS_PlayerEnter`?

2024-05-31 13:52 UTC, merged